import os
import ssl
from urllib.parse import urlparse

from redis.asyncio.connection import SSLConnection

from .base import *  # noqa: F403, F401

REDIS_TLS_URL = os.getenv("REDIS_TLS_URL", REDIS_URL)  # noqa: F405

if REDIS_PROTOCOL == "rediss" or "rediss" in REDIS_TLS_URL:  # noqa: F405
    # We need to set the certificate check to None, otherwise it is not compatible with
    # the `heroku-redis` addons. The URL generated by those addons is over a secured
    # connection with a self signed certificate. The redis broker could fail if the
    # certificate can't be verified.
    CELERY_REDBEAT_REDIS_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}

    # Required to get Channels v4 working with Heroku Redis over TLS.
    #
    # Heroku Redis serves a self-signed certificate, so certificate verification must be
    # disabled. The channels_redis layer also needs a *real* TLS connection class:
    # subclassing the plain `redis.asyncio.connection.Connection` (the old workaround for
    # https://github.com/django/channels_redis/issues/235) opens an unencrypted socket
    # against the TLS-only port, so the server immediately resets it ("Connection reset
    # by peer") and the real-time WebSocket can never establish. Use redis-py's
    # `SSLConnection` with certificate checks disabled instead.
    parsed_redis_url = urlparse(REDIS_TLS_URL)
    CHANNELS_REDIS_HOST = {
        "host": parsed_redis_url.hostname,
        "port": parsed_redis_url.port,
        "username": parsed_redis_url.username or None,
        "password": parsed_redis_url.password,
        "connection_class": SSLConnection,
        "ssl_cert_reqs": None,
        "ssl_check_hostname": False,
    }
    CHANNEL_LAYERS["default"]["CONFIG"]["hosts"] = [CHANNELS_REDIS_HOST]  # noqa: F405

    # The built in healthcheck does not handle customizing ssl_cert_reqs...
    INSTALLED_APPS.remove("health_check.contrib.redis")  # noqa: F405
    for CACHE in CACHES.values():  # noqa: F405
        CACHE["OPTIONS"]["CONNECTION_POOL_KWARGS"] = {"ssl_cert_reqs": None}

# Set the limit of the connection pool based on the amount of workers that must be
# started with a limit of 10, which is the default value. This is needed because the
# `heroku-redis:mini` doesn't accept more than 20 connections.
CELERY_BROKER_POOL_LIMIT = min(
    4 * int(os.getenv("BASEROW_AMOUNT_OF_WORKERS", "1")),  # noqa: F405
    10,
)
CELERY_REDIS_MAX_CONNECTIONS = min(
    4 * int(os.getenv("BASEROW_AMOUNT_OF_WORKERS", "1")),  # noqa: F405
    10,
)

# Run the Celery worker with the threads pool instead of the default prefork pool.
# Prefork spawns a separate child process for each concurrency slot in addition to the
# coordinator process. On Heroku's single all-in-one dyno that extra Python process
# costs ~150-200MB of resident memory while giving no extra throughput at concurrency 1
# (Baserow already runs a single combined worker here). The threads pool executes tasks
# inside the main worker process, preserving the same one-task-at-a-time behaviour while
# keeping the whole stack comfortably under the dyno's 1GB memory quota (avoiding R14,
# which previously destabilised the real-time WebSocket).
CELERY_WORKER_POOL = "threads"

HEROKU_ENABLED = True
